FROM openjdk:8

MAINTAINER gvanitha.shri@gmail.com

EXPOSE 80

ADD target/ExpenseTracker-Spring-1.0-SNAPSHOT.jar ExpenseTracker-Spring-1.0-SNAPSHOT.jar

ENTRYPOINT ["java","-jar","/ExpenseTracker-Spring-1.0-SNAPSHOT.jar"]