---
- hosts: servers
  tasks:
    - name: Installing requirements - wget, java
      yum:
        name: '{{item.packval}}'
        state: present
      with_items:
        - { packval: 'git'}
        - { packval: 'wget'}
        - { packval: 'java'}
        - { packval: 'maven'}

    - name: Adding jenkins.repo under /etc/repos.d - Updating io key
      command: '{{item.cmdval}}'
      with_items:
        - { cmdval: 'wget -O /etc/yum.repos.d/jenkins.repo http://pkg.jenkins.io/redhat-stable/jenkins.repo'}
        - { cmdval: 'rpm --import http://pkg.jenkins.io/redhat-stable/jenkins.io.key'}

    - name: Install jenkins
      yum: name=jenkins state=present

    - name: Starting jenkins
      service: name=jenkins enabled=yes state=started

    - name: Editing the config file
      lineinfile:
        path: /etc/sysconfig/jenkins
        regexp: '{{item.regexpval}}' #Line to Search
        line: '{{item.lineval}}' #Line to Replace
      with_items:
        - { regexpval: '^JENKINS_USER', lineval: 'JENKINS_USER=root'}
        - { regexpval: '^JENKINS_PORT', lineval: 'JENKINS_PORT=8083'}

    - name: Restarting Jenkins
      service: name=jenkins state=restarted

